version: "3.0"


services:
    mysql:
        image: mysql:5.5
        container_name: "${COMPOSE_PROJECT_NAME}_mysql"
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
            - "./docker/mysql/data:/docker-entrypoint-initdb.d/"
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - database
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

    php_apache:
        build: ./docker/phpapache/
        container_name: "${COMPOSE_PROJECT_NAME}_phpapache"
        ports:
            - 80:80
        volumes:
            - "${PROJECT_ROOT}:/var/www"
        networks:
            - database
            - server
        depends_on:
            - mysql



networks:
    database:
    server:
